@startuml

title
    =Stroom Architecture
    ==Example Two-Node Cluster (non-containerised deployment)
end title

'Define the various application ports
!stroom_port=8080
!stroom_proxy_port=8090

'Define all the nodes (services, actors, etc.)
node "Event generator" as event_producer <<application>>
node "User" as ui_client_browser <<web browser>>
node "API client" as api_client_app <<application>>
node "Upstream Stroom proxy" as remote_proxy <<application>>

node "Nginx load balancer" as nginx <<web server>>

rectangle "Proxy 'Cluster'" as proxy_cluster {
    storage "Proxy Node #1" {
        node "Local Stroom proxy" as stroom_proxy_local_1 <<java app>>
        nginx -[#Green]-> proxy_cluster : <color:Green>HTTP:stroom_proxy_port</color>\n<color:Green>/datafeed (proxy)</color>
    }

    storage "Proxy Node #2" {
        node "Local Stroom proxy" as stroom_proxy_local_2 <<java app>>
    }
}

rectangle "Stroom Cluster" as stroom_cluster {
    storage "Stroom Node #1" {
        node "Stroom node" as stroom_node_1 <<java app>>

        'Reverse proxy connections
        nginx -[#Green]-> stroom_cluster : <color:Green>HTTP:stroom_port</color>\n<color:Green>/datafeeddirect (stroom)</color>\n<color:Green>/api (stroom)</color>\n<color:Green>/ui (stroom)</color>
    }

    storage "Stroom Node #2" {
        node "Stroom node" as stroom_node_2 <<java app>>
    }

    stroom_proxy_local_1 .[#Purple].> stroom_cluster : <color:Purple>HTTPS (via Nginx)</color>\n<color:Purple>/datafeeddirect</color>\n<color:Purple>/api (stroom)</color>
    stroom_proxy_local_2 .[#Purple].> stroom_cluster : <color:Purple>HTTPS (via Nginx)</color>\n<color:Purple>/datafeeddirect</color>\n<color:Purple>/api (stroom)</color>
}

'Intra-cluster communication
stroom_node_1 <-[#Grey]-> stroom_node_2 : <color:Grey>HTTP:stroom_port</color>\n<color:Grey>Inter-node communication</color>

storage "MySQL Server" as stroom_all_dbs {
    database "stroom" as stroom_db
    database "stats" as stroom_stats_db
}

'DB connections
stroom_node_1 --> stroom_db : <color:DarkRed>TCP:3306</color>
stroom_node_1 --> stroom_stats_db : <color:DarkRed>TCP:3306</color>
stroom_node_2 --> stroom_db : <color:DarkRed>TCP:3306</color>
stroom_node_2 --> stroom_stats_db : <color:DarkRed>TCP:3306</color>

storage "Shared Storage" as shared_storage {
    folder "stroom-node-2"
    folder "stroom-node-1"
}

'Shared storage connections
stroom_node_1 --> shared_storage : <color:DarkRed>NFS/SMB</color>
stroom_node_2 --> shared_storage : <color:DarkRed>NFS/SMB</color>

'Client connections
ui_client_browser -[#Blue]-> nginx : <color:Blue>HTTPS</color>
api_client_app -[#Blue]-> nginx : <color:Blue>HTTPS</color>\n<color:Blue>/api (stroom)</color>
event_producer -[#Blue]-> remote_proxy : <color:Blue>HTTPS</color>\n<color:Blue>Event data</color>
remote_proxy -[#Blue]-> nginx : <color:Blue>HTTPS</color>\n<color:Blue>/datafeed</color>\n<color:Blue>/api (proxy)</color>

legend right
  <b>Types of traffic</b>

  <color:Blue>Client</color>
  <color:DarkRed>Direct</color>
  <color:Green>Reverse-proxied (unencrypted)</color>
  <color:Grey>Internal (unencrypted)</color>
  <color:Purple>Via Nginx</color>
endlegend

'hide empty members

@enduml
