@startuml
left to right direction

rectangle "Stream nnn" #Silver {
    rectangle "Part 1" #LightBLue {
        rectangle "Data" #Tomato {
            rectangle "Record 0" #Gold {
            }
            rectangle "Record 1" #Gold {
            }
            rectangle "Record 3" #Gold {
            }
        }
    }
}

@enduml

