@startuml
left to right direction
rectangle "Stream nnn" #Silver {
    rectangle "Part 1" #LightBlue {
        rectangle "Data" #Tomato {

        }
        rectangle "Meta" #SeaGreen {

        }
        rectangle "Context" #SlateBlue {

        }
    }

    rectangle "Part 2" #LightBlue {
        rectangle "Data " #Tomato {
        }
        rectangle "Meta " #SeaGreen {
        }
        rectangle "Context " #SlateBlue {
        }
    }

    rectangle "Part 3" #LightBlue {
        rectangle "Data  " #Tomato {
        }
        rectangle "Meta  " #SeaGreen {
        }
        rectangle "Context  " #SlateBlue {
        }
    }
}

@enduml
