@startuml

'title
'    =Data Sources
'end title

top to bottom direction
skinparam linetype ortho

rectangle "Search Documents" as search_docs {
    rectangle "Dashboard" as dashboard_doc {
        rectangle "Extraction Pipeline" as dash_extraction_pipe #line.dashed
    }
    rectangle "Query" as query_doc
    rectangle "Analytic Rule" as rule_doc
}

rectangle "View" as view_doc right of search_docs
{{
    database "Data source" as view_data_source
    rectangle "Extraction Pipeline" as view_extraction_pipe #line.dashed
}}
end rectangle

database "Data source" as data_source

search_docs -> view_doc
search_docs -> data_source

@enduml
