@startuml

title
    ==Stroom multi-node mixed-economy deployment
    Stroom services in Docker
    Stroom and MySQL on bare OS
end title

skinparam rectangle {
	roundCorner<<container>> 25
}

node dataload_client_host <<device>> {
    node "Event generator" as dataload_client_app <<application>>
}

node ui_client_host <<device>> {
    node "Web browser" as ui_client_browser <<web browser>>
}

'node stroom_host <<device>> {
'    node "stroom" as stroom_dropwiz <<java app>>
'}

node database_host <<device>> {
    database stroom_all_dbs <<mysql>> {
        storage "stroom" as stroom_db <<database>>
        storage "stats" as stroom_stats_db <<database>>
        storage "auth" as stroom_auth_db <<database>>
    }
}

node services_host <<device>> {
    rectangle nginx_container <<container>>{
        node "nginx" as nginx <<web server>>
    }
    rectangle stroom_auth_ui_container <<container>>{
        node "stroom-auth-ui nginx" as stroom_auth_ui_nginx <<web server>>
    }
    rectangle stroom_auth_service_container <<container>>{
        node "stroom-auth-service" as stroom_auth_service_dropwiz <<java app>>
    }
}

!function $concat($name, $id)
!return $name + $id
!endfunction

' Function to generate a stroom host with links to and from it
!function add_stroom_host($node_id)
    !$host_name=$concat("stroom_host_", $node_id)
    !$stroom_dropwiz_name=$concat("stroom_dropwiz_", $node_id)
    !$stroom_proxy_dropwiz_name=$concat("stroom_proxy_dropwiz_", $node_id)

    node $host_name <<device>> {
        node $concat("stroom", $node_id) as $stroom_dropwiz_name <<java app>>
        'node $concat("stroom-proxy", $node_id) as $stroom_proxy_dropwiz_name <<java app>>
    }
    ' Database connections
    $stroom_dropwiz_name --> stroom_db
    $stroom_dropwiz_name --> stroom_stats_db
    ' API Gateway connection
    $stroom_dropwiz_name --> nginx : HTTP?:????
    'Reverse proxy connections
    nginx --> $stroom_dropwiz_name : HTTP:8080\nRev. proxy
!endfunction

together {
    add_stroom_host("1")
    'add_stroom_host("2")
}

'DB connections
stroom_auth_service_dropwiz --> stroom_auth_db

'Client connections
ui_client_browser --> nginx : HTTPS:443\n/stroom/ui
dataload_client_app --> nginx : HTTPS:443\n/datafeed

'Reverse proxy connections
nginx --> stroom_auth_ui_nginx : HTTP:????\nRev. proxy
nginx --> stroom_auth_service_dropwiz : HTTP:????\nRev. proxy

stroom_auth_ui_nginx --> nginx : HTTP:????\nREST calls


' see http://plantuml.com/skinparam & https://github.com/plantuml/plantuml/pull/31

'skinparam handwritten true
'skinparam monochrome reverse
'skinparam backgroundColor DimGrey
'skinparam ClassBackgroundColor DimGrey
'skinparam ClassBorderColor WhiteSmoke
'skinparam backgroundColor transparent

' light theme
'skinparam backgroundColor LightGrey
'skinparam ClassBackgroundColor LightGrey
'skinparam ClassBorderColor CornflowerBlue
'skinparam DatabaseBackgroundColor LightGrey
'skinparam DatabaseBorderColor CornflowerBlue

'hide empty members

@enduml

